export const companyName = [];

export const companyTransaction = [
  {
    id: 0,
    transactionTo: '',
    transactionFrom: '',
    invoice_id: '',
    business_id: 0,

    // company_name_id: 0,
    // transactions: [
    //   {
    //     id: 0,
    //     remarks: 'Ram Le chokar lageko',
    //     year: 2020,
    //     month: 'Jan',
    //     day: 20,
    //     time: '8:59 AM',
    //     amount: 5000,
    //     status: 'dr',
    //     transaction_to: '',
    //     transaction_from: '',
    //     documents: [],
  },

  //     {
  //       id: 0,
  //       remarks: 'Ram Le chokar lageko',
  //       year: 2020,
  //       month: 'Jan',
  //       day: 20,
  //       time: '8:59 AM',
  //       amount: 5000,
  //       status: 'cr',
  //       transaction_to: '',
  //       transaction_from: '',
  //       documents: [],
  //     },

  //     {
  //       id: 0,
  //       remarks: 'Ram Le chokar lageko',
  //       year: 2020,
  //       month: 'Jan',
  //       day: 20,
  //       time: '8:59 AM',
  //       amount: 5000,
  //       status: 'dr',
  //       transaction_to: '',
  //       transaction_from: '',
  //       documents: [],
  //     },

  //     {
  //       id: 0,
  //       remarks: 'Ram Le chokar lageko',
  //       year: 2020,
  //       month: 'Jan',
  //       day: 20,
  //       time: '8:59 AM',
  //       amount: 5000,
  //       status: 'cr',
  //       transaction_to: '',
  //       transaction_from: '',
  //       documents: [],
  //     },

  //     {
  //       id: 0,
  //       remarks: 'Ram Le chokar lageko',
  //       year: 2020,
  //       month: 'Jan',
  //       day: 20,
  //       time: '8:59 AM',
  //       amount: 5000,
  //       status: 'dr',
  //       transaction_to: '',
  //       transaction_from: '',
  //       documents: [],
  //     },
  //   ],
  // },
  // {
  //   comId: 1,
  //   transactions: [
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'cr',
  //     },
  //     {
  //       description: 'Ram Le chokar lsdfd sdf dsf sdf dsf dsf df ageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'cr',
  //     },
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //   ],
  // },
  // {
  //   comId: 2,
  //   transactions: [
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //   ],
  // },
  // {
  //   comId: 3,
  //   transactions: [
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  //     {
  //       description: 'Ram Le chokar lageko',
  //       year: 2077,
  //       month: 'Baishak',
  //       day: 20,
  //       week: 'sunday',
  //       time: '8:59 AM',
  //       amount: 5000,
  //       account: 'dr',
  //     },
  // ],
  // },
];

export const bank = [
  {
    id: 0,
    name: 'Nic Asia',
    branch: 'Hetauda',
    logo: '',
  },
];

export const bankTransaction = [
  {
    id: 0,
    bank_id: 0,
    date: '2020-03-09',
    status: 'dr',
    amount: 9000,
    transactionTo: '',
    transactionFrom: '',
  },
];

export const sheller = [
  {
    id: 0,
    name: 'Radha Krishna Kutani Pisani Mill',
    address: 'Hetauda-8, Kamane',
    propiterName: 'Radhika Devi Upreti',
    panNumber: '093-23-9860',
    phone: '9845222614',
    website: 'https://www.rkmainali.com.np',
    email: 'radhikadeviupreti@gmail.com',
    zip: '44007',
    logo: '',
    description: 'This Is My Own Mill Company',
  },
];

export const invoice = [
  {
    id: 0,
    description: 'Mula',
    date: '2020-09-30',
    amount: 4000,
    status: 'cr',
    sheller_id: 0,
    customer_id: 0,
  },
];

export const expensies = [
  {
    id: 0,
    description: 'dudh kineko',
    date: '2056-7-8',
    amount: 30,
    status: 'dr',
    transactionTo: 'Others',
    transactionFrom: '',
  },
];

export const customer = [
  {
    id: 0,
    name: 'Pratima Upreti',
    phone: 9804202103,
    address: 'ktm-6',
    email: 'pratima@gmail.com',
    photo: '',
  },
];
