export const company_name = [];
export const company_transaction = [
  {
    company_name_id: 0,
    transactions: [
      {
        id: 0,
        remarks: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        time: '8:59 AM',
        amount: 5000,
        status: 'dr',
        transaction_to: '',
        transaction_from: '',
        documents: [],
      },
      {
        comContentId: 1,

        description: '2 bora pitho lera aako',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'cr',
      },
      {
        comContentId: 2,

        description: 'Kisna Sabjilai Deko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
    ],
  },
  {
    comId: 1,
    transactions: [
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'cr',
      },
      {
        description: 'Ram Le chokar lsdfd sdf dsf sdf dsf dsf df ageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'cr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
    ],
  },
  {
    comId: 2,
    transactions: [
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
    ],
  },
  {
    comId: 3,
    transactions: [
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
    ],
  },
];
