export const Com = [
  // {companyName: 'Mill', id: 0},
  // {companyName: 'Home Expenditure', id: 1},
  // {companyName: 'Bank', id: 2},
  // {companyName: 'tika', id: 7},
  // {companyName: 'Milk', id: 3},
];
export const ComContent = [
  {
    comId: 0,
    transactions: [
      {
        comContentId: 0,
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        comContentId: 1,

        description: '2 bora pitho lera aako',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'cr',
      },
      {
        comContentId: 2,

        description: 'Kisna Sabjilai Deko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
    ],
  },
  {
    comId: 1,
    transactions: [
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'cr',
      },
      {
        description: 'Ram Le chokar lsdfd sdf dsf sdf dsf dsf df ageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'cr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
    ],
  },
  {
    comId: 2,
    transactions: [
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
    ],
  },
  {
    comId: 3,
    transactions: [
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
      {
        description: 'Ram Le chokar lageko',
        year: 2077,
        month: 'Baishak',
        day: 20,
        week: 'sunday',
        time: '8:59 AM',
        amount: 5000,
        account: 'dr',
      },
    ],
  },
];
